### ISSUE TITLE
Add package description

### ISSUE THREAD

**Issue by lucascolley** [conda-forge/scipy-stubs-feedstock#1]
A description could (should) be added in the recipe under `about:` -> `description:`

**Comment by jorenham** [comment]
Does it support markdown?

**Comment by lucascolley** [comment]
I think different package browsers can render it differently, but yeah. https://github.com/conda-forge/python-feedstock/blob/245770e34f4fdbfa2a4f53113951888f369bae0e/recipe/meta.yaml#L351-L377 is rendered as https://prefix.dev/channels/conda-forge/packages/python.

**Comment by jorenham** [comment]
Is there perhaps a way to "include" the `README.md` then?

**Comment by lucascolley** [comment]
I'm not sure

**Comment by jorenham** [comment]
maybe something like this?
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files

**Comment by jorenham** [comment]
> maybe something like this? https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files

Tea that didn't work... see #2

I asked Claude to write me a description, and opened #3
